# Generated by Django 3.2.9 on 2021-12-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='Полное название')),
                ('title', models.CharField(max_length=3, verbose_name='Название')),
                ('description', models.FloatField(verbose_name='Сумма в KZT')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('search_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETED')], default='P', max_length=1, verbose_name='Статус')),
                ('items', models.JSONField(null=True, verbose_name='Результат')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма в EUR')),
            ],
            options={
                'verbose_name': 'Результат поиска',
                'verbose_name_plural': 'Результаты поиска',
                'ordering': ('amount',),
            },
        ),
    ]
