# Generated by Django 3.2.9 on 2021-12-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0002_alter_searchresult_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='items',
            field=models.JSONField(default=list, null=True, verbose_name='Результат'),
        ),
    ]
